// lib/PortSection/ConfigFile.dart
const String baseUrl = 'http://172.16.218.97:3000/';
const String registration = '${baseUrl}registration';
const String login = '${baseUrl}login';
const String addTodo = '${baseUrl}storeTodo';
const String getToDoList = '${baseUrl}getUserTodoList';
const String deleteTodo = '${baseUrl}deleteTodo';
const String getBloodReports = '${baseUrl}api/blood-reports/'; // Ensure this expects userId
const String addBloodReport = '${baseUrl}api/blood-reports/';
const String addPost = '${baseUrl}api/posts';
const String getPosts = '${baseUrl}api/posts';
const String likePost = '${baseUrl}api/likes';
const String getDoctors = '${baseUrl}doctors';
const String getStreaks = '${baseUrl}api/streaks/';
const String imageBaseUrl = baseUrl;
const String getSteps = '${baseUrl}api/steps/';
const String submitSteps = '${baseUrl}api/steps';
const String getHospitalCities = '${baseUrl}api/hospitals/cities';
const String getHospitalDistricts = '${baseUrl}api/hospitals/districts';
const String getHospitals = '${baseUrl}api/hospitals';